version: '3'
services:
  vendingmachine:
    container_name: vendingmachine
    build: .
    command: tail -f /dev/null

  memcached:
    container_name: memcached
    image: memcached:latest
    ports:
      - "11211:11211"
